openapi: 3.0.0
info:
  title: AgendApp API
  version: 1.0.0
  description: API para gestión de turnos y reservas con pagos

servers:
  - url: http://localhost:8080/api

paths:
  /auth/register:
    post:
      summary: Registro de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Usuario registrado

  /auth/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Token JWT

  /{userId}/topics:
    get:
      summary: Listar temáticas del usuario
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de temáticas
    post:
      summary: Crear nueva temática
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicRequest'
      responses:
        '201':
          description: Temática creada

  /{userId}/schedule:
    get:
      summary: Listar clases agendadas
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de clases
    post:
      summary: Crear clase
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleRequest'
      responses:
        '201':
          description: Clase creada

  /{userId}/billing/subscribe:
    post:
      summary: Crear suscripción mensual con Mercado Pago
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Link de pago generado

  /public/{username}/available-classes:
    get:
      summary: Ver calendario público
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Clases disponibles

  /public/{username}/reserve/{classId}:
    post:
      summary: Reservar clase públicamente
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: classId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicReservationRequest'
      responses:
        '200':
          description: Reserva realizada

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        fullName:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    TopicRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    ScheduleRequest:
      type: object
      properties:
        topicId:
          type: string
        date:
          type: string
          format: date-time
        durationMinutes:
          type: integer
        capacity:
          type: integer
    PublicReservationRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
