package com.reservalink.api.exception;

public enum BusinessErrorCodes {
    OFFERING_HAS_ACTIVE_BOOKINGS,
    SLOT_TIME_OVERLAPPED,
    UNIQUE_FIELD_ALREADY_EXISTS,
    NO_CAPACITY_AVAILABLE,
    RESOURCE_NOT_AVAILABLE,
    RESOURCE_HAS_ACTIVE_BOOKINGS,
    FEATURE_LIMIT_EXCEEDED,
    UNAUTHORIZED_RESOURCE_ACCESS,
    FEATURE_NOT_ENABLED,
    INVALID_PHONE_NUMBER,
    DELETE_OFFERING_CATEGORY_DEFAULT,
    OFFERING_CATEGORY_ALREADY_EXISTS
}
